export const PERMISSIONS = {
  USERS_READ: "users:read",
  USERS_MANAGE: "users:manage",
  APPOINTMENTS_CREATE: "appointments:create",
  APPOINTMENTS_READ_OWN: "appointments:read:own",
  APPOINTMENTS_READ_ANY: "appointments:read:any",
  APPOINTMENTS_UPDATE_OWN: "appointments:update:own",
  APPOINTMENTS_UPDATE_ANY: "appointments:update:any",
  APPOINTMENTS_OVERBOOK: "appointments:overbook",
  BARBERS_READ: "barbers:read",
  BARBERS_MANAGE: "barbers:manage",
  BARBER_SCHEDULES_MANAGE: "barber-schedules:manage",
  CATALOG_READ: "catalog:read",
  CATALOG_MANAGE: "catalog:manage",
  PAYMENT_METHODS_READ: "payment-methods:read",
  PAYMENT_METHODS_MANAGE: "payment-methods:manage",
  ORDERS_CREATE: "orders:create",
  ORDERS_READ: "orders:read",
  ORDERS_UPDATE: "orders:update",
  SALES_CREATE: "sales:create",
  INVENTORY_READ: "inventory:read",
  INVENTORY_MANAGE: "inventory:manage",
  FINANCE_MANAGE: "finance:manage",
  REPORTS_READ: "reports:read",
  DEVELOPMENT_ACCESS: "development:access",
  DEVELOPMENT_DEBUG: "development:debug",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
